SELECT 'last', elt(INTERVAL(INJURED_P_NUMBER, 0, 3, 5, 10), '事件-0', '事件-3', '事件-5', '事件-10') as P_LEVEL, count(EVENT_TYPE) as counts, SUM(INJURED_P_NUMBER) as INJURED
FROM EGOV_DUTY_SUBMIT_REPORT
WHERE EVENT_TYPE = '事件' AND EVENT_TIME>='2009-06-02' AND EVENT_TIME<='2021-06-14'
GROUP BY P_LEVEL
UNION(
    SELECT 'last', elt(INTERVAL(INJURED_P_NUMBER, 0, 3, 5, 10), '案件-0', '案件-3', '案件-5', '案件-10') as P_LEVEL, count(EVENT_TYPE) as counts, SUM(INJURED_P_NUMBER) as INJURED
    FROM EGOV_DUTY_SUBMIT_REPORT
    WHERE EVENT_TYPE = '案件' AND EVENT_TIME>='2009-06-02' AND EVENT_TIME<='2021-06-14'
    GROUP BY P_LEVEL
    UNION (
        SELECT 'last', elt(INTERVAL(INJURED_P_NUMBER, 0, 3, 5, 10), '环境污染-0', '环境污染-3', '环境污染-5', '环境污染-10') as P_LEVEL, count(EVENT_TYPE) as counts, SUM(INJURED_P_NUMBER) as INJURED
        FROM EGOV_DUTY_SUBMIT_REPORT
        WHERE EVENT_TYPE = '环境污染' AND EVENT_TIME>='2009-06-02' AND EVENT_TIME<='2021-06-14'
        GROUP BY P_LEVEL )
)
UNION

SELECT 'current', elt(INTERVAL(INJURED_P_NUMBER, 0, 3, 5, 10), '事件-0', '事件-3', '事件-5', '事件-10') as P_LEVEL, count(EVENT_TYPE) as counts, SUM(INJURED_P_NUMBER) as INJURED
FROM EGOV_DUTY_SUBMIT_REPORT
WHERE EVENT_TYPE = '事件' AND EVENT_TIME>='2010-06-02' AND EVENT_TIME<='2021-07-14'
GROUP BY P_LEVEL
UNION(
    SELECT 'current', elt(INTERVAL(INJURED_P_NUMBER, 0, 3, 5, 10), '案件-0', '案件-3', '案件-5', '案件-10') as P_LEVEL, count(EVENT_TYPE) as counts, SUM(INJURED_P_NUMBER) as INJURED
    FROM EGOV_DUTY_SUBMIT_REPORT
    WHERE EVENT_TYPE = '案件' AND EVENT_TIME>='2010-06-02' AND EVENT_TIME<='2021-07-14'
    GROUP BY P_LEVEL
    UNION (
        SELECT 'current', elt(INTERVAL(INJURED_P_NUMBER, 0, 3, 5, 10), '环境污染-0', '环境污染-3', '环境污染-5', '环境污染-10') as P_LEVEL, count(EVENT_TYPE) as counts, SUM(INJURED_P_NUMBER) as INJURED
        FROM EGOV_DUTY_SUBMIT_REPORT
        WHERE EVENT_TYPE = '环境污染' AND EVENT_TIME>='2010-06-02' AND EVENT_TIME<='2021-07-14'
        GROUP BY P_LEVEL )
)